### ISSUE TITLE
(bug) Icons not showing on build

### ISSUE THREAD

**Issue by jojobii-arks** [jojobii-arks/sturdy-dollop#5]
### Problem
Dumb stupid SVGs won't load
<img width="158" alt="image" src="https://user-images.githubusercontent.com/78003700/166083747-fdad6a6d-dc11-40ce-af1a-cb74d715e299.png">

### Tasks
- [ ] Create new component that handles NGS Icons
- [ ] Replace `<img>` for icon with new component, given property of icon desired, for all instances of icons.
#### Stretch
- [ ] Create tooltip for each effect.
- [ ] Create alt-text for each icon.

### Notes
If all icons are dependent on components, I shouldn't have to worry about needing a placeholder...
